# Generated by Django 3.2.12 on 2022-04-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='imgg', upload_to='pics'),
            preserve_default=False,
        ),
    ]
